name: DSI Studio Data Hub
on: 
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
      run_qsdr:
        description: 'Run QSDR'
        type: boolean
        default: true

jobs:    
  info:
    uses: actions/checkout@v3
    with:
      repository: 'data-openneuro/disease'
      path: 'openneuro-disease-repo'
    run: |
      # Checkout the other repository
      git checkout main
    uses: ./openneuro-disease-repo/.github/workflows/add_info.yml
    name: Access OpenNeuro
    with:
      dataset_id: ${{ inputs.dataset_id }} 
  nii2src:
    uses: ./openneuro-disease-repo/.github/workflows/nii2src.yml
    needs: info
    name: Call NII to SRC
    with:
      dataset_id: ${{ inputs.dataset_id }}      
          
  src_quality_check:
    uses: ./openneuro-disease-repo/.github/workflows/src_qc.yml
    needs: nii2src
    name: SRC Quality Check
    with:
      src_list: 'sz'
      dataset_id: ${{ inputs.dataset_id }} 

  reconstruction:
    uses: ./openneuro-disease-repo/.github/workflows/recon.yml
    needs: nii2src
    name: SRC to FIB
    with:
      dataset_id: ${{ inputs.dataset_id }}
      run_qsdr: ${{ inputs.run_qsdr }}
          
  database_construction:
    if: inputs.run_qsdr == true
    uses: ./openneuro-disease-repo/.github/workflows/create_db.yml
    needs: reconstruction
    strategy:
      matrix:
          metrics: ['qa','dti_fa']
    name: Create Database
    with:
      metrics: ${{ matrix.metrics}}
