name: DSI Studio Data Hub
on: 
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
      run_qsdr:
        description: 'Run QSDR'
        type: boolean
        default: true

jobs:    
  info:
    steps:
      - name: Checkout disease repo
        uses: actions/checkout@v3
        with:
          repository: 'data-openneuro/disease'
          path: 'disease-repo'
      - name: Run add_info workflow
        uses: ./disease-repo/.github/workflows/add_info.yml
        with:
          dataset_id: ${{ inputs.dataset_id }} 
  nii2src:
    needs: info
    steps:
      - name: Checkout disease repo
        uses: actions/checkout@v3
        with:
          repository: 'data-openneuro/disease'
          path: 'disease-repo'
      - name: Run nii2src workflow
        uses: ./disease-repo/.github/workflows/nii2src.yml
        with:
          dataset_id: ${{ inputs.dataset_id }}      
          
  src_quality_check:
    needs: nii2src
    steps:
      - name: Checkout disease repo
        uses: actions/checkout@v3
        with:
          repository: 'data-openneuro/disease'
          path: 'disease-repo'
      - name: Run src_qc workflow
        uses: ./disease-repo/.github/workflows/src_qc.yml
        with:
          src_list: 'sz'
          dataset_id: ${{ inputs.dataset_id }} 

  reconstruction:
    needs: nii2src
    steps:
      - name: Checkout disease repo
        uses: actions/checkout@v3
        with:
          repository: 'data-openneuro/disease'
          path: 'disease-repo'
      - name: Run recon workflow
        uses: ./disease-repo/.github/workflows/recon.yml
        with:
          dataset_id: ${{ inputs.dataset_id }}
          run_qsdr: ${{ inputs.run_qsdr }}
          
  database_construction:
    if: inputs.run_qsdr == true
    needs: reconstruction
    steps:
      - name: Checkout disease repo
        uses: actions/checkout@v3
        with:
          repository: 'data-openneuro/disease'
          path: 'disease-repo'
      - name: Run create_db workflow
        uses: ./disease-repo/.github/workflows/create_db.yml
        with:
          metrics: 'qa'
        strategy:
          matrix:
            metrics: ['qa','dti_fa']
